[package]
name = "img_combiner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"

[profile.release]
lto = true
strip = true
opt-level = 3
